export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const SIGNUP_LOGIN_SUCCESS = 'SIGNUP_LOGIN_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';

export const GET_ALL_BLOGS = 'GET_ALL_BLOGS';
export const GET_BLOG_BY_ID = 'GET_BLOG_BY_ID';
export const GET_BLOG_ERROR = 'GET_BLOG_ERROR';
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const CREATE_PROJECT_ERROR = 'CREATE_PROJECT_ERROR';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const UPDATE_PROJECT_ERROR = 'UPDATE_PROJECT_ERROR';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const DELETE_PROJECT_ERROR = 'DELETE_PROJECT_ERROR';
export const STATE_PROGRESS = 'STATE_PROGRESS';
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const UPLOAD_IMAGE_ERROR = 'UPLOAD_IMAGE_ERROR';
